language: objective-c

env:
  matrix:
    - MONO_VERSION="3.4.0"

install:
  - wget "http://download.mono-project.com/archive/${MONO_VERSION}/macos-10-x86/MonoFramework-MDK-${MONO_VERSION}.macos10.xamarin.x86.pkg"
  - sudo installer -pkg "MonoFramework-MDK-${MONO_VERSION}.macos10.xamarin.x86.pkg" -target /
  - mono src/.nuget/NuGet.exe install NUnit.Runners -Version 2.6.3 -OutputDirectory src/packages -ExcludeVersion

script: 
  - xbuild src/fantomas.sln /p:Configuration=Release
  - mono --runtime=v4.5 src/packages/NUnit.Runners/tools/nunit-console.exe src/Fantomas.Tests/bin/Release/Fantomas.Tests.dll

